### PR TITLE
Address various issues reported by Findbugs

### PR DESCRIPTION
**Pull request by sschuberth**
@goneall My contributions are done under the terms of the Apache License, version 2.0.

### CODE REVIEW

**Comment by sschuberth** [comment]
@ybronshteyn Of course you're also welcome to review and merge :-)

**Comment by goneall** [comment]
Finished reviewing the changes.  Overall a lot of good fixes and improvements :)  There is one commit I would like to consider removing 	"Remove the unused ArtifactOfProjectURI() method …	018d372" - I left a comment on the commit describing my reasoning.

**Comment by sschuberth** [comment]
Thanks. I've already dropped the `ArtifactOfProjectURI` commit form the PR. I can drop the one that removes `generatePackageVerificationCode`, too, if you like.

Also, you seem to have missed that I also renamed the public `HtmlToText` method to `htmlToText`. I guess for this the same rules apply, i.e. I should keep the original around and mark it as deprecated, or?

**Comment by goneall** [comment]
The renaming of HtmlToText is a possible issue, but since it is not part of the model / spec it is less likely that it is used externally, so I think it is OK to clean this up and keep the commit in.

**Comment by sschuberth** [comment]
Good, then the PR should be fine now in its current state, I guess.

**Comment by goneall** [comment]
Merged and pushed to git.spdx.org - should be sync'd soon

**Pull request closed without merging**
