### PR TITLE
Miscellaneous minor fixes and improvements for the LicenseExpressionParser

### PR DESCRIPTION
**Pull request by sschuberth**
@goneall My contributions are done under the terms of the Apache License, version 2.0.

### CODE REVIEW

**Comment by sschuberth** [comment]
@goneall Would you mind looking at this independently of PR #66?

**Comment by goneall** [comment]
@sschuberth  I'm waiting for the resolution on the + operator - seems like it is still pretty active on the spdx trhead.  If you could create a pull request without the + operator fix, I can merge that in.

**Comment by sschuberth** [comment]
@goneall This already *is* without the plus operator fix, hence I was asking for the merge.

**Comment by goneall** [comment]
Got it - I'll go ahead and merge it.  Somehow I missed the notification of the new  or modified pull request.

**Comment by goneall** [comment]
Merged to git.spdx.org - should sync with github soon

**Pull request closed without merging**
