### PR TITLE
ISSUE-6 Make line endings consistent with Git settings in repository

### PR DESCRIPTION
**Pull request by romeara**
(Switch request to be to merge into 'develop' - didn't notice it auto-picked master the first time)

Commit changes to line ends of files which are not compliant with the settings in the repository's /.gitattributes file.

This is a resolution to #6

### CODE REVIEW

**Comment by romeara** [comment]
Also, I'm not 100% sure how to "officially" mark my changes as contributed under the project license of Apache 2.0 (I believe all the files I altered already have the license header - is this sufficient?)

**Comment by kemitchell** [comment]
I did this: https://github.com/spdx/tools/pull/1#issuecomment-102524808

@goneall might've been happy without the signature, too.

**Comment by romeara** [comment]
I saw that this was done on develop, it was present in the branch I was working on. It appears that those changes were successful - I think git is trying to auto-handle line endings. But I think some of the files on the develop branch did not have their line endings corrected, as they are immediately marked as "changed" upon checkout - its possible they were already in the repository before you added the gitattributes file. This pull is an attempt to correct those files to be in line with the line ending policies you put in place (which look like they are correct, hence I think its the files, not the settings, that need to be corrected)

**Comment by romeara** [comment]
Based on @kemitchell 's comment, I will state:
My contributions are made available under the terms of the Apache License, version 2.0.

If you want the same signature he did in the pull request, just let me know and I'll try to generate it

**Comment by goneall** [comment]
Having some problems merging in the pull request:
git checkout -b romeara-develop develop
git pull https://github.com/romeara/tools.git develop
^ On this command Git is complaining that the files are already modified and will be overwritten by merge.  Even if I stash the changes, I get the same error.

Should I use a force option to override?

**Comment by goneall** [comment]
For the commit license - A comment by you indicating the changes are under the Apache 2.0 license is good enough.

**Comment by romeara** [comment]
Ironically, this is due to exactly what I am trying to fix - it marks the files as "modified" locally due to the line endings. And because I modified the same files, it complains. 

A friend has previously managed to get around this by making a one-character change in the github web GUI (this can be adding and removing a space). Git then re-saves the files with the proper line endings. 

It would be less labour-intensive it you can find a command to force-overwrite your "changes" with my pull request, as the pull request will actually make those "uncommitted modifications" disappear. Unfortunately I do not know the git command to do this off the top of my head, and a quick search hasn't turned up obvious candidates. 

The other option is to commit your local changes, then merge mine - this should result in the same file set as my pull request, as you'd be making the same commit, and git is much happier merging commits than it is merging a commit and "uncommitted local changes"

I added a comment above with the license statement, and will do that as standard practice on pull requests here in the future, based on @goneall and @kemitchell 's statements

**Comment by goneall** [comment]
OK - I think? I got it merged - If you could check it out and see if it resolved the issue.

I also merged to master.  We are switching back to developing on the master branch.

Question: What is the best way to document that we are back on master for current development?  Since we are done with the SPDX 2.0 work, we can probably just work with the single master branch.

**Comment by romeara** [comment]
I saw the "base your work on develop branch" in the CONTRIBUTING.md file - ("To submit a patch via GitHub, fork the repository, create a topic branch from develop for your work") I would change it there, and possibly include a small sentence in the ReadMe.md saying "see the CONTRIBUTING.ms" file for specifics on how to contribute.

I currently don't see any changes in the github repository - is there a delay in the mirror, or did hte changes fail to push from your local copy maybe?

**Comment by romeara** [comment]
So I was able to pull the changes, and it eliminated a lot of files - however, there appear to still be several, especially on master, when I view this on my windows machine. I will create another pull request off of master to resolve that - you may close this one as complete

**Pull request closed without merging**
