### PR TITLE
Fix (mixed) line ending issues in text files

### PR DESCRIPTION
**Pull request by sschuberth**
Some files were committed with CRLF endings, some even had mixed endings within the same file. Fix this.

### CODE REVIEW

**Comment by sschuberth** [comment]
@goneall WOuld you mind having a look, as I have other fixes in the pipeline that depend on this :-)

**Comment by goneall** [comment]
@ybronshteyn - Do you have any uncommitted changes?  I can merge these in, but I don't want to create a merge conflict if you are in the middle of some work.

**Comment by ybronshteyn** [comment]
@goneall, no. I meant to spin off a release on Tuesday, but got buried with
other stuff. I have no changes.

**Comment by goneall** [comment]
I'm having trouble merging the changes.  It seems there is something corrupted in git (or just pilot error).  When I try to do the merge on my local file system, I'm getting an error that local changes will be overwritten to src/org/spdx/rdfparser/model/SpdxPackage.java.  Note - I did not modify this file.  When I revert the changes (e.g. through checkout) and the changes show right back up again.  I deleted the entire directory and cloned from git.spdx.org and the same thing happened.  I also tried reset, committing and stashing - nothing seems to get rid of this "Modified" file.

@ybronshteyn  - if you get a chance, can you try merging in these changes?  I'm kind of stuck.

**Comment by sschuberth** [comment]
@goneall I had similar issues when authoring the changes. Some files were very broken, containing mixed line endings, which totally confused Git. To make my fix work it seems to be essential that you apply changes one by one, not through a merge. So try cherry-picking each individual commit in order, that should do it.

**Comment by goneall** [comment]
I'll give it a try

**Comment by sschuberth** [comment]
@goneall Any luck yet? It should be pretty straight forward if you configure an additional remote named e.g. "github" for your local working tree, and make Git fetch PRs from that remote similar to [here](https://gist.github.com/piscisaureus/3342247) (replace `origin` with `github` and adjust the repo URL, obviously). Then you could simply do `git cherry-pick c746cde 8d88a23 0b52167` and should be done.

Also, if you don't know it already, [Hub](https://hub.github.com/) might be of interest to you (see the section named "As an open-source maintainer").

**Comment by ybronshteyn** [comment]
Sorry, just saw this therad. Let me take a stab at it.

**Comment by goneall** [comment]
@sschuberth I found out I have to recover some of my local files after my failed attempt a merging on Saturday which will take a bit more time.  The github repo is a mirror of git.spdx.org/spdx-tools which also adds a bit of complexity to the process.  I'll wait and see if Yev is able to get things working.  If needed, I can spend some time this afternoon.

**Comment by sschuberth** [comment]
@goneall I'm aware the repo at GitHub is just a mirror, but the cool thing is, even if you initially cloned from http://git.spdx.org/spdx-tools.git, you can add the PRs from GitHub as a Git remote, integrate, push back to http://git.spdx.org/spdx-tools.git, and GitHub will automatically update. GitHub even closes PRs if it detects the code has been merged manually. There should be no need to explicitly close PRs.

**Comment by ybronshteyn** [comment]
I merged the diff white the whitespace=fix option. Tried making a clean clone of the repo, and none of the HTML or java files appeared modified. A small handful of other files did (.xls and RDF) and I addressed those in a separate commit. @sschuberth, could you do a clean pull and verify that you are now unblocked?

**Comment by sschuberth** [comment]
@ybronshteyn While I appreciate your help, it's unfortunate that you did not do a real `git merge` or `git cherry-pick` as I suggested above. Instead you seem to have squashed my three commits into one, and on top of that amended whitespace trimming to it. With this, it's impossible for me to easily and reliably tell whether my changes have been properly integrated.

In general, I noticed that this project does not seem to properly integrate PRs in a way that maintains authorship. Would you mind elaborating why that is?

**Comment by sschuberth** [comment]
Anyway, I have a follow-up at https://github.com/spdx/tools/pull/60.

**Comment by ybronshteyn** [comment]
@sschuberth, That was my bad. I had issues with the fetch, but I should have used the --author parameter when committing the diff. If I can, with all this line break instanity, I'll revert and re-commit your changes with the author tag.

**Comment by sschuberth** [comment]
> I'll revert and re-commit your changes with the author tag.

Please don't do that. I value a clean history a lot, an reverting and re-applying a commit for no apparent reason is just confusing for any readers of the history.

**Pull request closed without merging**
