### PR TITLE
Fix even more line ending issues

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by ybronshteyn** [comment]
Pulled in. Give the repos a while to sync.

**Comment by sschuberth** [comment]
Why is this commit now twice in the history, once [with your sign-off](http://git.spdx.org/?p=spdx-tools.git;a=commit;h=86336c5dfe64aae370f239918dfc9537ded5c41e), and once [without](http://git.spdx.org/?p=spdx-tools.git;a=commit;h=0b7f87a8a3b382718c4bfbb61b0e50dd07dc1de6)?

**Comment by ybronshteyn** [comment]
I missed the sign-off on the first time and did an amend to add it.

**Comment by sschuberth** [comment]
Well, that's exactly my point. You did not *amend* your local commit in the sense of `git commit --amend`, but you created an alternative history and [merged](https://github.com/spdx/tools/commit/12172b345b18d4e070ecb58722d291479a293c6d) them.

**Pull request closed without merging**
