### PR TITLE
Remove Restricted Package Use and Begin Switching to Standard Library Methods

### PR DESCRIPTION
**Pull request by romeara**
This request includes the replacement of a reference to StandardCharsets, which exists within a restricted package, with the Guava library equivalent. In addition, it replaces uses of a custom null-handling equals with an equivalent Guava method (the original method is deprecated and remains for backwards compatibility, at least for a couple releases)

My contributions are licensed under the Apache 2.0 license as required for contributions to this project

### CODE REVIEW

**Comment by yevster** [comment]
If we're going to move the codebase to Java 7, we might as well switch to
NIO's Standard Charsets. Guava's are soft-deprecated.

https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html

**Comment by romeara** [comment]
Agreed, but I forsee the Java-7 upgrade taking several releases to get approved for upgrade, since it's a non-trivial requirement for existing users to upgrade their applications if they haven't already done so (think IT organizations in large companies). I didn't want to gate the removal of custom implementations (and restricted packages) behind it. We can easily go back and remove soft-deprecated items once the library upgrades to Java 7

**Comment by yevster** [comment]
Merged into master (please wait for github to get synced). Alas, I do not seem to have the ability to close the pull request.

**Comment by romeara** [comment]
Confirmed, this has been merged

**Pull request closed without merging**
