### PR TITLE
Remove some dead stores to local variables

### PR DESCRIPTION
**Pull request by romeara**
Remove saves to variables which are never used (bad practice)

My contributions are licensed under the Apache 2.0 License as required for contributions to this project

### CODE REVIEW

**Comment by goneall** [comment]
These calls actually server a purpose - they are in the verification code and are called to make sure no exceptions occur.  If an exception occurs, the validation will fail.

I left the variables in there strictly for debugging purposes, but they can be removed.

A better solution would be to just call the method "get...()" and not assign it to a variable and add a comment "checking for exceptions" to explain why the call is there.

**Comment by romeara** [comment]
@goneall - the only "get" calls which I removed were to "getComment" - I explicitly checked that the only thing that call did was return a variable, it does not additional checking. Where I removed the assignment from an iterator, I kept the iter.getNext() call intact

**Comment by goneall** [comment]
@romeara - I just went back and reviewed the code and you are correct - these can be safely removed.

**Comment by goneall** [comment]
Merged into git.spdx.org - should show up on github on the next refresh

**Comment by romeara** [comment]
Awesome, thank you. And always better to check something like that before merging :)

**Pull request closed without merging**
