### PR TITLE
Fix NoCommentInputStream to work with multi-byte character encodings

### PR DESCRIPTION
**Pull request by sschuberth**
My contributions are done under the terms of the Apache License, version 2.0.

### CODE REVIEW

**Comment by sschuberth** [comment]
@goneall & @ybronshteyn Please have a look!

**Comment by goneall** [comment]
Reviewed it and looks OK to me.  I'd like Yev to also take a look before merging.
@ybronshteyn Could you review and do the pull request for this one?  I'm going to be offline Friday through Sunday.

**Comment by sschuberth** [comment]
@ybronshteyn Any update on the review progress?

**Comment by sschuberth** [comment]
@goneall I'm not getting any response from @ybronshteyn. Do you think this is good to merge still?

**Comment by goneall** [comment]
@sschuberth I'll take a look and merge this weekend

**Comment by goneall** [comment]
Merged to git.spdx.org - should be reflected on github soon

**Pull request closed without merging**
