### PR TITLE
ISSUE-6 Fix line endings in org.spdx.tag package

### PR DESCRIPTION
**Pull request by romeara**
Pull request to continue towards resolving #6 - as there are hundreds of files in the repository, of which all appear affected, I thought a good way to break it into manageable chunks would be to pick a package.

This resolves the line endings issue in the tag package. There are no other changes in this pull request.

All of the files appear modified on every line due to the nature of the issue.

My contributions are licensed under the Apache 2.0 license as required for contributions to this project.

### CODE REVIEW

**Comment by romeara** [comment]
Also, @goneall - would you like the rest of the packages queued up (in separate pull requests) all at once, or how I've been doing it, in sequence as each is accepted? I don't want to completely bury you in a bunch of requests, but if you'd rather do a bunch at once I can create and queue them a few pull requests at a time

**Comment by goneall** [comment]
The way you are doing it is fine.  Thanks for working on this!

**Comment by goneall** [comment]
Merged in the changes to git.spdx.org - should showup in github soon

**Comment by romeara** [comment]
No problem. I have a branch for each package waiting in queue - I'll continue putting them up in sequence since (I think) you said you'd prefer that instead of a bunch of pull requests at once :) I'll keep an eye on it and put them up as you review and merge each one.

**Pull request closed without merging**
