### PR TITLE
Fix a typo in the convertTagFileToRdf() method name

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

**Comment by goneall** [comment]
@sschuberth Could you just add a quick comment to the pull request that your contributions are offered under the Apache License 2.0 in addition to signing off (per https://github.com/spdx/tools/blob/master/CONTRIBUTING.md).  Thanks.
Gary

**Comment by sschuberth** [comment]
My contributions are done under the terms of the Apache License, version 2.0.

**Comment by sschuberth** [comment]
@goneall Done, also for my other pending PRs. Though I have to say it's rather unusual to require that. None of the Apache 2.0 licensed projects I've contributed to so far did require a similar statement, esp. not *in addition* to a sign-off.

**Comment by goneall** [comment]
Merged and pushed back to git.spdx.org - should be sync'd soon.

**Pull request closed without merging**
